import Head from "next/head";

const UpdateReport=() => {
    return <>
    <Head>
        <title> Coach report Update</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>coach report Update</h1>
      </main>
    </>
}

export default UpdateReport