import reportModel from "@/model/reportModel";
import dbConnect from "@/utils/dbConnect";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { ParsedUrlQuery } from "querystring";

function UpdateReport() {
  return (
    <>
      <Head>
        <title> Coach report Update</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>coach report Update</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context: {
  params?: { id: string } | ParsedUrlQuery | undefined;
}) => {
  await dbConnect();
  const id = context.params?.id;
  console.log(id);
  const coach_report = await reportModel.findById(id);
  return {
    props: {},
  };
};

export default UpdateReport;
