import { CoachData } from "@/utils/interface";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useForm, SubmitHandler } from "react-hook-form";

const AddCoachDetails: NextPage = () => {
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitSuccessful },
  } = useForm<CoachData>();

  useEffect(() => {
    if (isSubmitSuccessful) {
      reset({ coachType: "", coachNumber: "", returnDate: "" });
    }
  }, [reset, isSubmitSuccessful]);

  const onSubmit: SubmitHandler<CoachData> = (data) => {
    console.log(data);
    fetch("/api/addcoach", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => {
      res.json().then((d) => console.log(d));
    });
  };

  return (
    <>
      <Head>
        <title>Add Coach Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Add Coach details Form page</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div>
            <label>Coach Type:</label>
            <input {...register("coachType", { required: true })} />
            {errors.coachType && <span> Coach Type required</span>}
          </div>
          <div>
            <label>Coach Number:</label>
            <input {...register("coachNumber", { required: true })} />
            {errors.coachNumber && <span>Coach Number required</span>}
          </div>
          <div>
            <label>Return Date:</label>
            <input {...register("returnDate")} />
          </div>
          <div>
            <label>AC Plant:</label>
            <input {...register("acPlant")} />
          </div>
          <div>
            <label>Inverter:</label>
            <input {...register("inverter")} />
          </div>
          <div>
            <label>Pump 1:</label>
            <input {...register("pump1")} />
          </div>
          <div>
            <label>Pump 2:</label>
            <input {...register("pump2")} />
          </div>
          <div>
            <label>RRU PP:</label>
            <input {...register("rruPP")} />
          </div>
          <div>
            <label>RRU NPP:</label>
            <input {...register("rruNPP")} />
          </div>
          <div>
            <input type="submit" />
          </div>
        </form>
      </main>
    </>
  );
};

export default AddCoachDetails;
