import Head from "next/head";

const UpdateCoach = () => {
  return (
    <>
      <Head>
        <title> Coach data Update</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>coach data Update</h1>
      </main>
    </>
  );
};

export default UpdateCoach;
