import CoachModel from "@/model/CoachModel";
import reportModel from "@/model/reportModel";
import dbConnect from "@/utils/dbConnect";
import Head from "next/head";

function Home({
  data,
}: {
  data: {
    _id: string;
    reportDetails: string;
    escortingFitter: string;
    coachNumber: string;
    coachType: string;
    date: string;
  }[];
}) {
  return (
    <>
      <Head>
        <title>Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>home page</h1>
        <ol>
          {data.map((d) => (
            <li key={d._id}>
              <div>
                <h4>
                  {d.coachNumber}-{d.coachType}
                </h4>
              </div>
              <div>
                <span>report : {d.reportDetails}</span>
              </div>
              <div>
                <span>escorting fiter : {d.escortingFitter}</span>
              </div>
              <div>
                <span>date : {d.date}</span>
              </div>
            </li>
          ))}
        </ol>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  await dbConnect();
  await CoachModel.find();
  const reportList = await reportModel
    .find({})
    .populate("coach")
    .sort({ date: -1 });

  const data = reportList.map((rl) => {
    return {
      _id: rl._id,
      reportDetails: rl.reportDetails,
      escortingFitter: rl.escortingFitter,
      coachNumber: rl.coach.coachNumber,
      coachType: rl.coach.coachType,
      date: rl.date,
    };
  });

  return {
    props: { data: JSON.parse(JSON.stringify(data)) },
  };
}

export default Home;
