import { CoachData } from "@/utils/interface";
import type { NextPage } from "next";
import Head from "next/head";
import { useForm, SubmitHandler } from "react-hook-form";

const AddCoachDetails: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CoachData>();

  const onSubmit: SubmitHandler<CoachData> = (data) => console.log(data);

  return (
    <>
      <Head>
        <title>Add Coach Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Add Coach details Form page</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div>
            <label>Coach Type:</label>
            <input {...register("coachType", { required: true })} />
            {errors.coachType && <span> Coach Type required</span>}
          </div>
          <div>
            <label>Coach Number:</label>
            <input {...register("coachNumber", { required: true })} />
            {errors.coachNumber && <span>Coach Number required</span>}
          </div>
          <div>
            <input type="submit" />
          </div>
        </form>
      </main>
    </>
  );
};

export default AddCoachDetails;
