import type { NextPage } from "next";
import Head from "next/head";

const UpdateCoachData: NextPage = () => {
  return (
    <>
      <Head>
        <title> Coach report Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>coach report</h1>
      </main>
    </>
  );
};

export default UpdateCoachData;
