import dbConnect from "@/utils/dbConnect";
import Coach from "model/CoachModel";
import Head from "next/head";

type dType = {
  coachNumber: string;
  coachType: string;
};

function CoachList({ list }: { list: dType[] }) {
  return (
    <>
      <Head>
        <title>Coach List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Coach List page</h1>
        <ul>
          {list.map((l) => (
            <li key={l.coachNumber}>
              {l.coachNumber}- {l.coachType}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

export async function getStaticProps() {
  await dbConnect();
  const coachList = await Coach.find({}).select("-__V");
  const data: dType[] = coachList.map((d) => {
    return {
      coachNumber: d.coachNumber,
      coachType: d.coachType,
    };
  });

  return {
    props: {
      list: data,
    },
  };
}
export default CoachList;
