import dbConnect from "@/utils/dbConnect";
import Coach from "model/CoachModel";
import Report from "model/reportModel";
import Head from "next/head";
import Link from "next/link";

type dType = {
  _id: string;
  coachNumber: string;
  coachType: string;
};

function CoachList({ list }: { list: dType[] }) {
  return (
    <>
      <Head>
        <title>Coach List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Coach List page</h1>
        <ul>
          {list.map((l) => (
            <li key={l._id}>
              <Link href={`/coachlist/${l._id}`} passHref>
                <a>
                  {l.coachNumber}- {l.coachType}
                </a>
              </Link>
              -
              <Link href={`/form/updatecoach/${l._id}`} passHref>
                <a>update coach details</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  await dbConnect();
  const coachList = await Coach.find({}).select("-__V");
  const data: dType[] = coachList.map((d) => {
    return {
      _id: d._id.toString(),
      coachNumber: d.coachNumber,
      coachType: d.coachType,
    };
  });

  return {
    props: {
      list: data,
    },
  };
}
export default CoachList;
